# Generated by Django 3.2.9 on 2021-11-30 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignacion',
            new_name='Actuacion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='anio',
        ),
        migrations.AddField(
            model_name='alumno',
            name='anio',
            field=models.IntegerField(default=0.0004948045522018803),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(through='curso.Actuacion', to='curso.Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
